### ISSUE TITLE
why are you spamming

### ISSUE THREAD

**Issue by asottile** [jakedent/fluddy#1]
how did you get my email, what mailing list have you created, why does your logo look so... please cease whatever wacky spamming you're doing and delete my email address

![Screenshot_20200210-075303_Gmail](https://user-images.githubusercontent.com/1810591/74165790-779db780-4bda-11ea-8f2b-6d606e4511d0.jpg)

**Comment by jakedent** [comment]
Emails from Github. 

Apologies.

**Comment by asottile** [comment]
wtf, you realize how intrusive that is? and for what?

**Comment by jakedent** [comment]
I did not, huge apologies - just trying to get some eyes on the project.

**Comment by asottile** [comment]
christ

use twitter / HN Show / r/python / LITERALLY ANYTHING ELSE

**Comment by jakedent** [comment]
Apologies again man.
