### ISSUE TITLE
Don't spam people

### ISSUE THREAD

**Issue by adamchainz** [jakedent/fluddy#2]
Why did you email me?

**Comment by jakedent** [comment]
Apologies, just trying to get some feedback on the project.

**Comment by adamchainz** [comment]
Yeah, and I'd be happy to do that if you approached me personally! I guess you've harvested peoples emails from a repo (every Flask contributor??) and spammed them with mailchimp, from the other issue #1. The Python community is welcoming but you won't make many internet friends that way. I suggest you send out an apology email immediately saying you have unsubbed everyone.

**Comment by jakedent** [comment]
Should have done so. I'll send an email now. 

Apologies again.
